source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.1'
# Use mysql as the database for Active Record
gem 'mysql2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails', '~> 2.1.4'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development
gem 'devise'
gem 'haml-rails'
gem 'jquery-datatables-rails', git: 'git://github.com/rweng/jquery-datatables-rails.git'
gem "nested_form"

#uploader gem 
gem "paperclip", "~> 4.1"


#For bootstrap
gem 'bootstrap_form'
gem 'bootstrap-multiselect-rails4', '~> 0.0.1'
gem 'bootstrap-sass'
# Bootstrap with sass support
gem "jquery-validation-rails"

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
gem "omniauth-google-oauth2"

# Faker gem for fake data generation
gem 'faker'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
 gem 'debugger', group: [:development, :test]

gem 'thin'

group :development, :test do
  gem 'rspec-rails', '~> 3.0' # Rspec helps writing test cases 
  gem "factory_girl_rails", "~> 4.0" # Generats test data like fixutures
  gem 'capybara' # Helps to simulate senario . Makes easy to write test grammer
  gem 'shoulda-matchers' # Makes validations easy to write in spec models
  gem 'launchy' # Helps execute commands easily like save and open page
  gem 'database_cleaner' # It cleans the database when required
  gem 'selenium-webdriver' # Automated browser which help simulate the senario writen on test cases
  gem 'simplecov', :require => false # shows coverage of your test cases
  gem 'fuubar'

  gem 'rack_session_access' # gem Helps to create a session access for tests

  #Guard For Automated test to be updated Faster without stoping 
  gem 'rb-fsevent', :require => false if RUBY_PLATFORM =~ /darwin/i
  gem 'guard-rspec'
  gem 'guard-livereload'
  #Guard For Automated test to be updated Faster without stoping 
end