source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# Use mysql as the database for Active Record
gem 'mysql2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bootstrap-sass'
gem 'bootstrap_form'
gem 'haml-rails'
gem "html2haml"

gem 'devise'
gem 'devise_invitable', '~> 1.3.4'
gem "wice_grid", '3.4.2'
gem "pundit"
gem 'figaro'
gem 'thin'
gem "paperclip", "~> 4.2"

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'debugger'
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'simplecov', require: false
  gem 'rubocop'
  gem 'fabrication'
  gem 'metric_fu', require: false
  gem 'brakeman', require: false
  gem 'guard-rails'  
  gem 'guard-livereload'
  gem 'faker'
  gem 'shoulda-matchers'
  gem 'capybara' # Helps to simulate senario . Makes easy to write test grammer
  gem 'launchy' # Helps execute commands easily like save and open page
  gem 'selenium-webdriver' # Automated browser which help simulate the senario writen on test cases
  gem 'simplecov', :require => false # shows coverage of your test cases
  gem 'fuubar'
  gem 'rack_session_access' # gem Helps to create a session access for tests
end