# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3b135cc6ea4034727f9cc76c6feb3cd8e1f65bf0d3c67c7b4df7dfb2a673d7c1852441418eb17b1db87e3bbc3d86b8d97edf37bd20718cc27993e0b897f9305

test:
  secret_key_base: b3d122f00eb00c096c6e01084a6cfd4347ecc365d9ef09fa749eaef5423ef15512702f9a43be97335a64a100ac1de6e498f677513d6925837c38ea99b8e961cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
