# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a42523d191c5592fa1484af37c3d9391869b929e982f3d4df3a736820a9478147f412b21f5d04af2bcb152da031170e80437f35c9bdd377532f5ef090e94d81

test:
  secret_key_base: 541f376949f0bf4937c2439cd205fdf12b3c22c42706bd14dd97996671ad065ff1bd1aba764329d41f8a1b4d607467db324e8ee013f383bb100d83ef42d2ace8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
